# Numpy is the core library for scientific computing in python

In [1]:
import numpy as np

In [2]:
a=np.array([1,23,4,44])
b=np.array(([1.4,2,4],[4,5,5]), dtype = float)
a, b

(array([ 1, 23,  4, 44]),
 array([[1.4, 2. , 4. ],
        [4. , 5. , 5. ]]))

## Initial Placeholders

In [3]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.ones((2,3,4), dtype = np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [6]:
np.arange(10,25,5)

array([10, 15, 20])

In [7]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [9]:
np.full((2,3),7) #creating constant array of 7

array([[7, 7, 7],
       [7, 7, 7]])

In [11]:
np.eye(2) #create identity matrix of 2 x 2

array([[1., 0.],
       [0., 1.]])

In [19]:
e=np.random.random((2,3))
e


array([[0.38711645, 0.81037221, 0.95704267],
       [0.74261574, 0.30360743, 0.64652647]])

In [23]:
np.empty((3,2)) #create a empty array

array([[0.38711645, 0.81037221],
       [0.95704267, 0.74261574],
       [0.30360743, 0.64652647]])

## Saving and Loading on disk

In [25]:
np.save('my_array', a)
np.savez('array.npz', a, b)
np.load('my_array.npy')

array([ 1, 23,  4, 44])

In [27]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

.. warning::

    Setting ``arr.dtype`` is discouraged and may be deprecated in the
    future.  Setting will replace the ``dtype`` without modifying the
    memory (see also `ndarray.view` and `ndarray.astype`).

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
ndarray.astype : Cast the values contained in the array to a new data-type.
ndarray.view : Create a view of the same data but a different data-type.
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


## inspecting your array

In [31]:
a.shape # array dimension

(4,)

In [32]:
len(a)

4

In [35]:
b.ndim #number of array dimension

2

In [37]:
e.size  #nmber of array element

6

In [38]:
b.dtype

dtype('float64')

In [40]:
b.dtype.name #name of data type

'float64'

In [41]:
b.astype(int) #convert array to other d type

array([[1, 2, 4],
       [4, 5, 5]])

## data type

- np.int64
- np.float32
- np.complex
- np.bool
- np.string
- np.unicode -> fixed-length unicode type


## array mathematics

In [55]:
a= np.array([1,3,4])
b=np.array([(4,5,6), (12,45,5)])
g= a -b
g

array([[ -3,  -2,  -2],
       [-11, -42,  -1]])

In [56]:
np.subtract(a,b)

array([[ -3,  -2,  -2],
       [-11, -42,  -1]])

In [57]:
b + a 

array([[ 5,  8, 10],
       [13, 48,  9]])

In [58]:
np.add(a,b)

array([[ 5,  8, 10],
       [13, 48,  9]])

In [59]:
a / b #division

array([[0.25      , 0.6       , 0.66666667],
       [0.08333333, 0.06666667, 0.8       ]])

In [60]:
np.divide(a,b)

array([[0.25      , 0.6       , 0.66666667],
       [0.08333333, 0.06666667, 0.8       ]])

In [61]:
a * b

array([[  4,  15,  24],
       [ 12, 135,  20]])

In [62]:
np.multiply(a,b)

array([[  4,  15,  24],
       [ 12, 135,  20]])

In [64]:
np.exp(a)

array([ 2.71828183, 20.08553692, 54.59815003])

In [65]:
np.sqrt(a)

array([1.        , 1.73205081, 2.        ])

In [66]:
np.sin(a)

array([ 0.84147098,  0.14112001, -0.7568025 ])

In [68]:
np.cos(b)

array([[-0.65364362,  0.28366219,  0.96017029],
       [ 0.84385396,  0.52532199,  0.28366219]])

In [69]:
np.log(a)

array([0.        , 1.09861229, 1.38629436])

In [76]:
a.dot(b) #must have same shape

(2, 3)

## comparison

In [77]:
a ==b

array([[False, False, False],
       [False, False, False]])

In [78]:
a < 2

array([ True, False, False])

## aggregate functions

In [79]:
a.sum()

np.int64(8)

In [80]:
a.min()

np.int64(1)

In [82]:
b.max(axis=0)

array([12, 45,  6])

In [83]:
b.cumsum(axis=1)

array([[ 4,  9, 15],
       [12, 57, 62]])

In [84]:
b.mean()

np.float64(12.833333333333334)

In [86]:
np.median(b)

np.float64(5.5)

In [87]:
np.corrcoef(a) #correlation coefficient

np.float64(1.0)

In [88]:
np.std(b)

np.float64(14.622091353686569)

## copying arrays

In [91]:
h = a.view() # create a view of the array with the same data
h

array([1, 3, 4])

In [92]:
np.copy(a) #create the cpy of an array.npz

array([1, 3, 4])

In [94]:
h = a.copy() #deep copy of an array
h

array([1, 3, 4])

In [98]:
b.sort(axis=0)
b

array([[ 4,  5,  6],
       [ 5, 12, 45]])

## subsetting, slicing, indexing

In [104]:
a[2] #select an element of the 2nd index

np.int64(4)

In [109]:
b[1,2]

np.int64(45)

In [111]:
a[0:2] #slicing of index o and 2

array([1, 3])

In [112]:
b[0:1,2] #select items at rows 0 and 1 in column 1

array([6])

In [113]:
b[1:]

array([[ 5, 12, 45]])

In [115]:
b[1,...] # same as b[1,:,:]

array([ 5, 12, 45])

In [116]:
b[: :-1]

array([[ 5, 12, 45],
       [ 4,  5,  6]])

In [119]:
a[a<2]

array([1])

## Array Manipulation

In [123]:
b

array([[ 4,  5,  6],
       [ 5, 12, 45]])

In [127]:
i = np.transpose(b) #permute array dimensions
i.T

array([[ 4,  5,  6],
       [ 5, 12, 45]])

In [129]:
b.ravel() #flattn the array

array([ 4,  5,  6,  5, 12, 45])

In [131]:
b.reshape(3,-2) #reshape but do not change data 

array([[ 4,  5],
       [ 6,  5],
       [12, 45]])

In [136]:
a

array([1, 3, 4])

In [140]:
np.append(a,6)

array([1, 3, 4, 6])

In [141]:
np.insert(a, 1, 5)

array([1, 5, 3, 4])

In [142]:
np.delete(a,[1])

array([1, 4])

In [143]:
a

array([1, 3, 4])

In [146]:
d=np.array([1,7,20])
d

array([ 1,  7, 20])

In [147]:
np.concatenate((a,d), axis=0)

array([ 1,  3,  4,  1,  7, 20])

In [149]:
np.hsplit(a,3) #spliting array

[array([1]), array([3]), array([4])]