# Numpy

NumPy—short for Numerical Python—is a powerful library that provides efficient tools for working with arrays and performing mathematical computations. It serves as the foundation for many scientific and data-driven applications. 

## One dimentional Arrays  

In [2]:
import numpy as np

In [26]:
#introduction with creating arrays
#create zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
#create array of ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(10, 3.5) #polulate a certain number

array([3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5])

In [10]:
a=np.array([1,2,3,5,6,7])

a

array([1, 2, 3, 5, 6, 7])

In [32]:
a[2]=19  #how to access array and change the array in the second index 

a

array([ 1,  2, 19,  5,  6,  7])

In [14]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.linspace(0,200,10) #line space of number from zero to the limit

array([  0.        ,  22.22222222,  44.44444444,  66.66666667,
        88.88888889, 111.11111111, 133.33333333, 155.55555556,
       177.77777778, 200.        ])

## Mult-dementional arrays

In [23]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
np.ones((6,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [31]:
n=np.array([
        [1,2,3],
        [4,5,6],
        [7,8,9]
])

n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
n[0,2] = 20  #accessing array and change the element

n

array([[ 1,  2, 20],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [37]:
n[2]=[1,1,1]
n

array([[ 1,  2, 20],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [39]:
n[:,2]=[0,12,2]  # full colon means access the whole rows
n

array([[ 1,  2,  0],
       [ 4,  5, 12],
       [ 1,  1,  2]])

## Randomly generated arrays

In [45]:
#use seed if you want to make the results reproducible
np.random.seed(2)   
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [46]:
#randn stands for “random normal” (standard normal distribution).
np.random.seed(2)   
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [48]:
#time with 100 if you want positive integers.
np.random.seed(2)   
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [50]:
np.random.seed(2)   
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations 

In [52]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [53]:
a + 1

array([1, 2, 3, 4, 5])

In [55]:
a*100

array([  0, 100, 200, 300, 400])

In [56]:
a /100

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [60]:
b= (10 + (a * 2)) ** 2 /100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [61]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

## Comparison operations 

In [62]:
a

array([0, 1, 2, 3, 4])

In [63]:
a >= 2

array([False, False,  True,  True,  True])

In [64]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [65]:
a > b 

array([False, False,  True,  True,  True])

In [66]:
a[a > b ]

array([2, 3, 4])

## Summarizing Operations

In [67]:
a

array([0, 1, 2, 3, 4])

In [68]:
a.min()

np.int64(0)

In [69]:
a.max()

np.int64(4)

In [71]:
a.sum()

np.int64(10)

In [72]:
a.mean()

np.float64(2.0)

In [73]:
a.std()

np.float64(1.4142135623730951)

In [74]:
n

array([[ 1,  2,  0],
       [ 4,  5, 12],
       [ 1,  1,  2]])

In [75]:
n.sum()

np.int64(28)

In [76]:
n.min()

np.int64(0)