## Linear algebra refleshing 

## vector operations 

In [50]:
import numpy as np

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


In [51]:
U= np.array([2,4,5,6])

U

array([2, 4, 5, 6])

In [52]:
u=np.array([1,0,0,2])

In [7]:
U + u

array([3, 4, 5, 8])

In [8]:
2 * U

array([ 4,  8, 10, 12])

In [9]:
U * u

array([ 2,  0,  0, 12])

## Multiplication
  - Vector-vector Multiplication(dot product)
  - Vector-matrix Multiplication
  - Matrix-matrix Multiplication

- Vector-vector Multiplication(dot product)

In [27]:
u=np.array([2,7,5,6])
v=np.array([3,4,8,6])
u.shape[0]
u + v

array([ 5, 11, 13, 12])

In [31]:
def vector_vector_multiplication(u,v):
    assert u.shape[0]==v.shape[0]

    n=u.shape[0]

    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
        
    return result
    
    

In [32]:
vector_vector_multiplication(u, v)

np.float64(110.0)

In [34]:
#in np we use dot product
u.dot(v)

np.int64(110)

- Vector-matrix Multiplication

In [38]:
U= np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1],
])

U.shape

(3, 4)

In [40]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows= U.shape[0]

    result= np.zeros(num_rows)

    for i in range(num_rows):
        result[i]= vector_vector_multiplication(U[i],v)

    return result
    
    


In [41]:
matrix_vector_multiplication(U, v)

array([98., 31., 35.])

In [42]:
U.dot(v)

array([98, 31, 35])

- Matrix-matrix Multiplication

In [46]:
V=np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0],
])

In [47]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi= V[:,i]
        Uvi= matrix_vector_multiplication(U , vi)
        result[:, i]= Uvi
    return result
    

In [48]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [49]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity matrix 

  U.I= U,  IU=U

In [56]:
I=np.eye(3)

In [57]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [58]:
Vs= V[[0,1,2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [60]:
Vs_inv=np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [61]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])